Repository harshkasyap/FileServer, pull requests merged in 2019-07, with the labels that each got.

#4 Adding Dockerfile for Instant Deployment
  prod/docker/dockerfile
  views/index.ejs
Labels: enhancement

#3 Fix wrong filename on delete prompt
  views/index.ejs
Labels: bug

#5 Docker Documentation
  README.md
Labels: documentation

#6 Chat Support In File Sharing
  .gitignore
  fileServer.js
  package.json
  views/index.ejs
Labels: enhancement

#7 Refractor Chat Application
  .gitignore
  fileServer.js
  prod/windows/runInBackground.vbs
  scripts/query.js
  scripts/script.js
  styles/style.css
  views/index.ejs
Labels: good first issue
